//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectV.DataAccessLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLStatementsForCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLStatementsForCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectV.DAL.Properties.SQLStatementsForCommon", typeof(SQLStatementsForCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM [dbo].[common] WHERE thing_id = @thing_id.
        /// </summary>
        internal static string CountItemsById {
            get {
                return ResourceManager.GetString("CountItemsById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [dbo].[common].
        /// </summary>
        internal static string DeleteAllItems {
            get {
                return ResourceManager.GetString("DeleteAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [dbo].[common] WHERE thing_id = @thing_id.
        /// </summary>
        internal static string DeleteItemById {
            get {
                return ResourceManager.GetString("DeleteItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[common] (thing_id, title, vote_count, vote_average) VALUES (@thing_id, @title, @vote_count, @vote_average).
        /// </summary>
        internal static string InsertItem {
            get {
                return ResourceManager.GetString("InsertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT thing_id, title, vote_count, vote_average FROM [dbo].[common].
        /// </summary>
        internal static string SelectAllItems {
            get {
                return ResourceManager.GetString("SelectAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT thing_id, title, vote_count, vote_average FROM [dbo].[common] WHERE thing_id = @thing_id.
        /// </summary>
        internal static string SelectItemById {
            get {
                return ResourceManager.GetString("SelectItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[common] SET title = @title, vote_count = @vote_count, vote_average = @vote_average WHERE thing_id = @thing_id.
        /// </summary>
        internal static string UpdateItemById {
            get {
                return ResourceManager.GetString("UpdateItemById", resourceCulture);
            }
        }
    }
}
